import './globals.css'
import Navigation from '../components/Navigation'
import { roboto } from './font'

export const metadata = {
  title: 'Next JS 13 app',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>😑</title>
      </head>
      <body className={roboto.className}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
